spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/${POSTGRES_DB:contactdb}?socketTimeout=5
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: false

  main:
    banner-mode: off

server:
  port: 8080
  servlet:
    context-path: /api